### ISSUE TITLE
Mostrar número e complemento do endereço nos e-mails transacionais

### ISSUE THREAD

**Issue by fabisoccol** [deivisonarthur/OSC-Magento-Brasil#139]
Olá pessoal,

Verifiquei que, por algum motivo, o número e o complemento preenchido pelo cliente no OSC não estão sendo enviados nos e-mails transacionais.

Alguém poderia me ajudar a resolver este problema? Já procurei em tudo que foi lugar e não encontrei!

Desde já agradeço a todos vocês.

**Comment by rafaelstz** [comment]
Primeiro passo é configurar o endereço para 4 linhas em:

> Admin : Sistema > Configuração > Clientes > Configuração > "Opções de
> Nome e Endereço"

As linhas vão ser:

```
street1 = endereço
street2 = numero
street3 = complemento
street4 = bairro
```

As variáveis são:

```
{{if street1}}{{var street1}}<br />{{/if}}
{{depend street2}}{{var street2}}<br />{{/depend}}
{{depend street3}}{{var street3}}<br />{{/depend}}
{{depend street4}}{{var street4}}<br />{{/depend}}
```

Para saber mais sobre essas variáveis poderá consultar no site oficial **Magento** [nesse link](http://www.magentocommerce.com/knowledge-base/entry/defining-transactional-variables).
