### ISSUE TITLE
Ajuda! Não calcula frete quando o usuário já tem endereço cadastrado

### ISSUE THREAD

**Issue by rebecapf** [deivisonarthur/OSC-Magento-Brasil#150]
Olá!

Estou com um problema ao finalizar o pedido. Quando o cliente se loga e entra na página do OSC, no bloco de frete aparece a mensagem "Por favor, corrija o CEP digitado, ele não está correto.", porém no endereço está tudo certo.
Se eu desabilito "Enviar para o mesmo endereço de cobrança" ele calcula certo, se habilito novamente ele continua certo... o problema está quando o cliente não fez nada, só entrou no OSC e já tem endereço cadastrado...

Alguém pode me ajudar? Por favor!

**Comment by rafaelstz** [comment]
Aparece algo no console?

**Comment by rebecapf** [comment]
Desculpa minha ignorância, mas onde exatamente é o console?

No log aparece assim:
2016-01-14T12:19:23+00:00 DEBUG (7): pedroteixeira_correios [87]: Invalid Zip Code

Queria saber em qual página ele envia o CEP para o módulo do pedro teixeira pra saber como está indo... sabe me dizer?

Outra coisa... vejo em outros sites que os endereços cadastrados aparecem como radiobutton, o meu está como drop down, será que pode ser isso? Como consigo alterar pra radio?

**Comment by rebecapf** [comment]
Rafael, descobri o problema!

Estava testando com meu usuário padrão, e nele eu tinha cadastrado o endereço pelo admin do magento e não selecionei as opções Endereço de Cobrança Principal e Endereço de Entrega Principal... depois que fiz isso resolveu tudo!

Muito obrigada pela atenção!
