### ISSUE TITLE
Erro ao finalizar o pagamento 

### ISSUE THREAD

**Issue by fechino** [deivisonarthur/OSC-Magento-Brasil#25]
Primeiramente, gostaria de agradecer pelo excelente trabalho ao desenvolver este modulo.

Fiz e refiz a instalação normalmente sem maiores problemas.

Mas o que está acontecendo quando preencho todas as informações de cadastro e ao clicar no Botão 
'Finalizar Compra " 

abre uma janela pequena, tipo "poupap"  com a seguinte informação

"The Date of Birth is required, The Tax/vat number is required "

OBS: Mesmo preenchendo a data de aniversário ou até mesmo desabilitando a mesma aparece a mesma mensagem.

inclusive já ativei o Campo CPF/CNPJ pelo TaxVat  para "SIM" mas não está funcionando.

Vocês poderiam me ajudar.

O download fiz diretamente no site www.http://onestepcheckout.com.br  - dia 07/11/2012

a versão que estou usando do magento é 1.4.1.1

o site é www.shopzero.com.br 

Grato

Danilo

**Comment by Vampre** [comment]
Amigo, você instalou a versão 3.2 ou 4 pro do OSC?

Já tentou ir no Admin em Sistema > configuração > Clientes > Configurações > Opções de nomes e endereço e colocar os campos CPF e Data de nascimento como opcionais?

Se não der certo, você terá que abrir o arquivo billing.phtml e achar os inputs da data de nascimento e CPF (pelo taxvat ou não) e ver o que está declarado no atributo "class". Se for o caso retira o "required".

Só uma pergunta. Onde está hospedado esta sua loja? Achei o carregamento das páginas bem rápidos!

Abraço

**Comment by deivisonarthur** [comment]
Show vampre você é o que esta contribuindo mais ao osc. Gostaria de te colocar também como responsável do projeto. 

Me add bo skype deivisonarthur

Enviado via iPhone

Em 07/11/2012, às 22:22, Vampre notifications@github.com escreveu:

**Comment by fechino** [comment]
Vampre,

Cara, muito obrigado pela sua ajuda.

Como baixei direto do site http://onestepcheckout.com.br/ no site informa que a Versão Atual: Final 3.0.2
Solucionei seguindo seus passos de CPF e Data como opcionais.

Fiz um teste de compra e finalizei tranquilo. ( espero que esta versão não de problemas futuros )

Com relação a hospedagem deste site está na King Host. ( venho utilizando a instalação automática deles a 3 anos e nunca tive problemas sérios. ) no momento eles trabalham com a versão instalada do magento 1.4 e 1.5 ambas já traduzidas e com o modulo dos correios e pag seguro já instalados.

Abraço

**Comment by Vampre** [comment]
Cara, que bom que conseguiu resolver. Realmente o módulo é muito bom e se você souber um pouco de PHP e da arquitetura do magento, pode personalizar ele bastante.

Meu OSC mesmo já está cheio de códigos novos! Bem personalizado. Quando vier alguma novidade do Deivison atualizando o módulo, terei que adicionar na unha para não sobrescrever o que já fiz. hehehehehe

Se já solucionou seu problema, coloque esta issue como resolvida (só para deixar as coisas mais organizadas aqui no Git)

Deivison, já irei te adicionar no Skype. Abraço
