### ISSUE TITLE
Sugestão de melhorias : Como manipular os campos de registro do cliente pelo admin

### ISSUE THREAD

**Issue by thalesviolakis** [deivisonarthur/OSC-Magento-Brasil#32]
Olá Deivison,

Gostaria de saber se tem como ocultar os campos de registro do cliente em Admin : Customer > Manage Customer > Account Information > Account Information  e logo em baixo em  Edit Customer's Address

Existem campos de texto que não são usados geralmente pelos brasileiros  

Prefix,  Middle Name / Initial , Suffix , TaxVat , uma vez que estamos usando os eu campo de CPF, 
E como você criou um campo Empresa, o campo Company também ficou em duplicidade porém vazio, uma idéia legal seria ocultar esses campos afim de melhorar esta parte.

Não é uma reclamação é uma sugestão de melhorias, eu não sei como proceder para executar da melhor forma possível estas partes .

Obrigado!!

**Comment by deivisonarthur** [comment]
Opa brother feliz natal!

Procede sim os campos nome do meio e taxvat vc pode ocular eles pela adm do magento. Enguanto o empresa eu add nome fantasia no que eu lembro 

Pode ficar a voltade para ocultar os campos nao compromete o osc

Em 2013 irei fazer uma versao top que substituira a anterior, e penso em fazer com outro sistema de osc

Enviado via iPhone

Em 25/12/2012, às 16:06, thalesviolakis notifications@github.com escreveu:

**Comment by thalesviolakis** [comment]
Obrigado
