### ISSUE TITLE
Falta opção "usuário já registrado"

### ISSUE THREAD

**Issue by overrideow** [deivisonarthur/OSC-Magento-Brasil#34]
Estou com um problema no OSC que não aparece a opção para as pessoas que já fizeram compra uma vez no site se logarem e nao precisar colocar os dados novamente.  Segue a imagem
Alguem sabe como resolver?
![erroosc](https://f.cloud.github.com/assets/3227854/54204/63ec2c5e-5a87-11e2-8987-629f19f8ea6d.JPG)

**Comment by overrideow** [comment]
Instalei novamente do zero, sem nenhum modulo e o problema persiste.

**Comment by deivisonarthur** [comment]
Opa brother troque onepagecheckout.phtml por esse arquivo aqui
https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/blob/master/app/design/frontend/base/default/template/onepagecheckout/onepagecheckout.phtml

**Comment by overrideow** [comment]
Deu certo!

Cara não tenho como agradecer!

Com certeza irei contribuir para o projeto!

Atenciosamente

Thiago Ferreira
  ----- Original Message -----
