### ISSUE TITLE
Não encontrei o tutorial

### ISSUE THREAD

**Issue by olavocarvalho** [deivisonarthur/OSC-Magento-Brasil#39]
Boa tarde, estou muito interessado em instalar o módulo porém a página http://www.deivison.com.br/blog/2012/08/11/osc-magento-brasil-magento-one-step-checkout-free-e-normatizado-para-o-brasil/ mostra no tópico "Tutorial para instalação e tratamentos de erros:" ele retorna para a mesma página e eu não chego no tutorial.

Pode me ajudar a acessar este tutorial??? obrigado.

**Comment by deivisonarthur** [comment]
Opa amigo basta extrair os arquivos em suas respectivas pastas, ao entrar
na administração vc verá o erro 404 ao clicar no link do modulo, mas isso é
normal no Magento, bastará vc sair da adm e entrar novamente que tudo volta
ao normal ;)

  [image: logo]
_Deivison Arthur Serpa__,
Gerente de Tecnologia e E-commerce do Grupo FFernandes
(21) 9203-8986 / (21) 2242-3885 / (21) 4063-8781
https://shop.pisosecarpetes.com.br
 https://www.pisosecarpetes.com.br/_http://www.deivison.com.br

_Contatos Web:_
_Skype *:  deivisonarthur
*MSN *: deivisonarthur@hotmail.com
*Facebook_:  facebook.com/deivisonarthurhttps://www.facebook.com/deivisonarthur

_Twitter_: @deivisonarthur
*Outros Contatos em *http://meadiciona.com/deivisonarthur
 [image: WordPress] http://www.deivison.com.br/blog Último post do meu
blog:Ngnix – Aprenda a criar subdominios, restringir acesso e colocar senha
nos diretórioshttp://www.deivison.com.br/blog/2013/01/22/ngnix-aprenda-a-criar-subdominios-restringir-acesso-e-colocar-senha-nos-diretorios/
Read morehttp://www.deivison.com.br/blog/2013/01/22/ngnix-aprenda-a-criar-subdominios-restringir-acesso-e-colocar-senha-nos-diretorios/|
My bloghttp://www.deivison.com.br/blog
[image: Share on
Facebook]http://www.facebook.com/sharer.php?u=http%3A%2F%2Fwww.deivison.com.br%2Fblog%2F2013%2F01%2F22%2Fngnix-aprenda-a-criar-subdominios-restringir-acesso-e-colocar-senha-nos-diretorios%2F
[image:
Share on Twitter]https://twitter.com/intent/tweet?text=Ngnix%20%E2%80%93%20Aprenda%20a%20criar%20subdominios%2C%20restringir%20acesso%20e%20colocar%20senha%20nos%20diret%C3%B3rios%20%20(via%20%40wisestamp)
  Get this email app!
http://www.wisestamp.com/apps/wordpress?utm_source=extension&utm_medium=email&utm_term=wordpress&utm_campaign=apps

  http://br.linkedin.com/pub/deivison-arthur/1b/35/468
 Free signature tool.
http://r1.wisestamp.com/r/landing?promo=32&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_32
CLICK
HERE TO GET IT.http://r1.wisestamp.com/r/landing?promo=32&dest=http%3A%2F%2Fwww.wisestamp.com%2Femail-install%3Futm_source%3Dextension%26utm_medium%3Demail%26utm_campaign%3Dpromo_32

Em 24 de janeiro de 2013 14:09, olavocarvlho notifications@github.comescreveu:

> Boa tarde, estou muito interessado em instalar o módulo porém a página
> http://www.deivison.com.br/blog/2012/08/11/osc-magento-brasil-magento-one-step-checkout-free-e-normatizado-para-o-brasil/mostra no tópico "Tutorial para instalação e tratamentos de erros:" ele
> retorna para a mesma página e eu não chego no tutorial.
> 
> Pode me ajudar a acessar este tutorial??? obrigado.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deivisonarthur/OSC-Magento-Brasil/issues/39.

## 

Atenciosamente

"  É melhor esperar que um programador produtivo torne-se disponível do que
esperar que o primeiro programador disponível torne-se produtivo! "

**Comment by LuizUltra** [comment]
deivisonarthur
Estou com o mesmo problema mencionado acima, não consigo ver o tutorial e já apei os ficheiros por ftp, limpei o cache, inclusive a pasta var e não aparece nada no backend.
