### ISSUE TITLE
Inserir/alterar campos no formulario de cadastro

### ISSUE THREAD

**Issue by esloch** [deivisonarthur/OSC-Magento-Brasil#41]
Gostaria de saber qual os arquivos que tenho que editar para inserir novos campos no formulario de cadastro, e alterar a opcao de check para combo em pessoa fisica ou juridica.

Grato

Sandro

**Comment by vissoci** [comment]
@esloch Conseguiu resolver isso?

**Comment by esloch** [comment]
Olá @apzeiro, não sei a que onda por magento, faz muito tempo, vou fechar esta issue.
Agradecido.

> @esloch Conseguiu resolver isso?
