### ISSUE TITLE
Botão Finalizar compra não aparece no checkout e OSC dá erro "Dados inválidos"

### ISSUE THREAD

**Issue by soraia** [deivisonarthur/OSC-Magento-Brasil#56]
Olá pessoal ontem instalei e testei o OSC no meu site de teste e funcionou muito bem, porém  quando instalei na produção ele não aparece o botão finalizar compra no carrinho de compras e quando clico no finalizar compra (link superior do site) ele entra com a página do OSC com formulário em branco e com a mensagem: dados inválidos sem ter digitado nenhum dado e não carrega a página toda.

O meu site de teste fica na locaweb e o da produção no hostgator, não sei se tem algo a ver ou algum plugin ou configuração pode estar conflitando.

Desde já agradeço se alguém puder me ajudar.

![03 Mar 26 08 48](https://f.cloud.github.com/assets/3974235/302643/7c7866f0-960c-11e2-87dd-67363c913ee1.jpg)
![04 Mar 26 08 48](https://f.cloud.github.com/assets/3974235/302645/82780998-960c-11e2-9637-539e52f7d8de.jpg)

**Comment by ejtomaz** [comment]
eai deu certo?
