### ISSUE TITLE
Campo Identidade / RG

### ISSUE THREAD

**Issue by matsyll** [deivisonarthur/OSC-Magento-Brasil#58]
Bom dia à todos!

 Primeiramente, obrigado aos contribuidores do projeto que lançaram essa versão totalmente gratuita e adaptada à nossa realidade!
Venho usando o módulo há mais de 2 meses em ambiente de testes, e agora, na fase final de testes do meu site venho enfrentando alguns problemas com ele.

No Brasil não há uma padronização do número de RG, e o módulo realiza algumas validações, não deixando alguns clientes registrarem.

Exemplo, em MINAS GERAIS, todos os RG's seguem a formatação: "MG-11111111111"
E o módulo não aceita letras. Está correto que bastaria o cliente remover o MG do cadastro, no entanto, faz parte do costume regionalista incluir o "MG" já que faz parte do documento oficial.

Acredito que tenha outros estados que possuam uma formatação diferente do habitual de SP e de outros estados.

Como vendo muito para o estado de MG, isso é um problema grave para mim.

Como posso remover essa validação do campo Identidade? Ou remover todo o campo identidade, já que ao meu ver, não possui necessidade.

Agradeço a resposta dos mais experientes!

Abraços

**Comment by claudio5678** [comment]
Boa tarde,

Você pode tentar alterar as configurações
em app/code/local/DeivisonArthur/OnepageCheckout/etc/config.xml
Fiz um teste rápido aqui e colocando o parametro rgiregistro como "hidden"
o campo identidade já não aparece no form do OSC.
Também não houve problemas na validação de server-side. Mas há outros
contextos como o formulário clássico de cadastro de usuário então convém
testar bem.

[]s, Claudio

2013/3/27 matsyll notifications@github.com

> Bom dia à todos!
> 
> Primeiramente, obrigado aos contribuidores do projeto que lançaram essa
> versão totalmente gratuita e adaptada à nossa realidade!
> Venho usando o módulo há mais de 2 meses em ambiente de testes, e agora,
> na fase final de testes do meu site venho enfrentando alguns problemas com
> ele.
> 
> No Brasil não há uma padronização do número de RG, e o módulo realiza
> algumas validações, não deixando alguns clientes registrarem.
> 
> Exemplo, em MINAS GERAIS, todos os RG's seguem a formatação:
> "MG-11111111111"
> E o módulo não aceita letras. Está correto que bastaria o cliente remover
> o MG do cadastro, no entanto, faz parte do costume regionalista incluir o
> "MG" já que faz parte do documento oficial.
> 
> Acredito que tenha outros estados que possuam uma formatação diferente do
> habitual de SP e de outros estados.
> 
> Como vendo muito para o estado de MG, isso é um problema grave para mim.
> 
> Como posso remover essa validação do campo Identidade? Ou remover todo o
> campo identidade, já que ao meu ver, não possui necessidade.
> 
> Agradeço a resposta dos mais experientes!
> 
> Abraços
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deivisonarthur/OSC-Magento-Brasil/issues/58
> .

## 

*
Cláudio Luiz Ferreira
*

**Comment by matsyll** [comment]
Obrigado pela resposta cláudio..

mas somente setar o rgiregistro como "hidden" não funcionou..

Na verdade funcionou, mas acarretou alguns problemas..

O nome do cliente não aparece em "Últimos Pedidos" como você pode ver na imagem:
http://www.69intencoes.com.br/pedido.jpg

E o cliente não realiza o cadastro do cliente. Ou seja, a compra é finalizada, mas a conta de cliente não é criada.

**Comment by matsyll** [comment]
Bem, consegui resolver o problema. Mantive o campo, mas tirei a validação do campo, agora aceitando todos os caracteres. Nenhum erro novo surgiu. Está tudo normal.

Exceto pelo fato que o rg não fica gravado no admin, erro comum à todos do módulo, estou utilizando essa ultima atualização, onde suposto havia sido corrigida, mas também não corrigiu pra mim.

**Comment by claudio5678** [comment]
Bom dia,

O problema com o campo RG não estar sendo gravado foi solucionado, mas
repare que é na versão 4 do OSC:
https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro

Mas o problema do RG é simples de ser resolvido, no arquivo billing.phtml,
trocar os atributos name e id do campo RG para name="billing[rg]" id="rg"

No mais, sugiro que compartilhe sua solução de remover a validação do
campo, pode ser útil para mais alguém.

Att, Claudio

2013/4/1 matsyll notifications@github.com

> Bem, consegui resolver o problema. Mantive o campo, mas tirei a validação
> do campo, agora aceitando todos os caracteres. Nenhum erro novo surgiu.
> Está tudo normal.
> 
> Exceto pelo fato que o rg não fica gravado no admin, erro comum à todos do
> módulo, estou utilizando essa ultima atualização, onde suposto havia sido
> corrigida, mas também não corrigiu pra mim.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deivisonarthur/OSC-Magento-Brasil/issues/58#issuecomment-15747533
> .

## 

*
Cláudio Luiz Ferreira
*

**Comment by matsyll** [comment]
Bom dia Claúdio!

Eu utilizei justamente essa versão, instalei em um ambiente de testes e realmente não notei que havia sido solucionado não, como já estava cansado, posso ter cometido algum erro. Irei avaliar com mais calma hoje.

Irei postar a solução sim, só estou realizando mais testes para ver se não surgiu algum outro bug...

abraços

**Comment by claudio5678** [comment]
Fiz vários testes antes desse último commit, justamente em uma loja simples
(1.7.0.2) só com um produto cadastrado e o OSC instalado.
Durante o desenvolvimento, alguns campos foram problemáticos e tiveram que
ter diversos testes (em diferentes browsers) até fechar a versão atual.
Mas a parte do RG funcionou desde o primeiro fix, que foi postado em
https://github.com/deivisonarthur/OSC-Magento-Brasil-4-Pro/issues/4#issuecomment-14570613
Resumindo é só trocar o name / id conforme msg anterior.

No mais, sua colaboração é sempre bemvinda, aguardamos seu post, obrigado.

2013/4/2 matsyll notifications@github.com

> Bom dia Claúdio!
> 
> Eu utilizei justamente essa versão, instalei em um ambiente de testes e
> realmente não notei que havia sido solucionado não, como já estava cansado,
> posso ter cometido algum erro. Irei avaliar com mais calma hoje.
> 
> Irei postar a solução sim, só estou realizando mais testes para ver se não
> surgiu algum outro bug...
> 
> abraços
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deivisonarthur/OSC-Magento-Brasil/issues/58#issuecomment-15772476
> .

## 

*
Cláudio Luiz Ferreira
*

**Comment by matsyll** [comment]
Cláudio, refiz os testes, foi falha minha ontem. Está gravando sim!!!

Para retirar a validação do campo identidade, você deve editar a linha 147 do billing.phtml que está localizado nos diretórios: app\design\frontend\default\shopper\template\onepagecheckout\onepage

trocar a seguinte trecho do arquivo original (da versão 4.0.2):

?>" class="input-text t1 validate-number <?php if($identidade === 'required'){ echo ' required-entry';} ?>" /

POR:

 ?>" class="input-text t1 <?php if($identidade === 'required'){ echo ' required-entry';} ?>" />

Mudança bem simples de se fazer, essa mudança irá alterar apenas o formulário de registro durante o checkout, é necessário editar mais alguns arquivos de painel de controle e outras páginas de registro, coisa que eu ainda não fiz. No entanto, o grande problema já está solucionado.

Podem ver na imagem, o registro do RG no admin, com números, letras e pontuação.
http://www.69intencoes.com.br/rg.jpg

Agora meu próximo passo será descobrir para gravar o nome do cartão de crédito, no módulo free que existe da cielo. Se alguém souber, agradeço...

Abraços

**Comment by claudio5678** [comment]
Que bom que funcionou, 

Sobre a validação entendi o problema. Provavelmente a melhor correção seria incluir "validate-number" denrto do IF, assim: 
<code>
?>" class="input-text t1 <?php if($identidade === 'required'){ echo ' validate-number required-entry';} ?>" />
</code>

**Comment by bbthemes** [comment]
Estou com um problema parecido, só não vejo a necessidade de se ter esse campo como "required". Não consegui retira-lo dos formularios, mas pelo menos com essa solução apresentada acima, posso não validado.

Obrigado aos Mantenedores, valeu!!

**Comment by flavioea** [comment]
eu acabei de fixar esta solução em meu OSC, porém fiz uma alteração que em primeira vista parece pertinente... achei q por bem, deixar sem nenhuma validação dá uma má impressão no ponto de vista técnico, por exemplo a possibilidade de caracteres especiais...
como temos até mesmo em SP o caso do dígito X, talvez o ideal seria trocar 

class="input-text t1 validate-number

por

class="input-text t1 validate-alphanum

tornando a validação alfanumérica...

o q pensei foi em criar um campo SSP já q todo RG tem seu órgão emissor e então setar a máscara para o campo... mas apesar de interessante, acho q polui o ambiente visual, já q no meu caso o OSC está muito "apertadinho"...
