### ISSUE TITLE
TEMPLATE APARECE UMA UNICA COLUNA 

### ISSUE THREAD

**Issue by roxhb** [deivisonarthur/OSC-Magento-Brasil#89]
O que devo mexer para o layout volte a 3 Colunas devo alterar a page.phtml ou algum .css?

Por favor me explique passo a passo o  que fazer...

**Comment by Randolphlima** [comment]
Tenta reinstalar o modulo, aconteceu comigo esses dias quando sem querer apaguei uma div no billing.phtml
Depois que reinstalei o modulo ele voltou a apresentar as três colunas normalmente.

Vale lembrar que antes de fazer qualquer modificação ou instalação e bom fazer um backup dos arquivos e do db, caso de "Xabu" você tem o backup feito.

t+

**Comment by roxhb** [comment]
Randolphlima obrigado por responder. Mas no meu caso no tema default ele funciona adequadamente mas no tema que escolhi, não. Não sei mais a quem recorrer estou desesperado. o tema que estou usando é magicshoes. 

Abraços

**Comment by Randolphlima** [comment]
Rox, eu dei uma olhada no site do teu template e la diz que ele e compativel com a versão " Compatible with 1.4.x, 1.5.x". Bem provavel que essa estrutura de três colunas seja apenas na versão 1.6.x+ do template. O template default e um exemplo disso, ele e feito para a versão 1.6.x 1.7.x do magento, por isso funciona normalmente. Caso não tenha outro template o jeito vai ser reestruturar o checkout dele para três colunas.

t+

**Comment by roxhb** [comment]
Corrigi de uma forma meio tosca mas ta valendo.

**Comment by romuloff** [comment]
@roxhb 

Como você corrigiu ?
Estou tendo problema tambem e está bem dificil pois tem que alterar css que é utilizado em outras páginas.
Se conseguiu resolver colocando atributos somente no css do OSC poderia por favor compartilhar ?

Grato
Atenciosamente

**Comment by thizanella** [comment]
Eu consegui corrigir, mas agora está louco o checkout, o arquivo onepagecheckout.phtml que alterei, mudou sozinho, e quando subo o alterado ele continua o original, mesmo excluindo ele o checkout continua funcionando. Já desabilite cache, entrei em outros computadores e não vai.
