### ISSUE TITLE
Hack??

### ISSUE THREAD

**Issue by mateussouzaweb** [deivisonarthur/OSC-Magento-Brasil#9]
Deivison, 

What is that?
https://github.com/deivisonarthur/OSC-Magento-Brasil/blob/master/app/design/frontend/base/default/template/onepagecheckout/cart/noItems.phtml#L1

:D

**Comment by deivisonarthur** [comment]
Go! Decoder!!! rs http://www.tareeinternet.com/scripts/decrypt.php

Imagina se fosse um hack, já tem +800 pessoas usando rs, mas não não é! É o arquivo noItems.phtml com um link para o projeto.

E ai vai dar essa honra de ter um link no noItems remetendo para o site do projeto?

**Comment by mateussouzaweb** [comment]
Hehe, e porque você não deixou isso visível? Quando eu vi eu estranhei... :)

**Comment by deivisonarthur** [comment]
O pessoal tira rs

**Comment by mateussouzaweb** [comment]
Rs, o problema do Open Source é isto... o pessoal faz o que quer.

**Comment by deivisonarthur** [comment]
e ai testou a nova versao brother?

**Comment by thalesviolakis** [comment]
Deivison, testei sua versão , e encontrei uma falha, ele cadastra o campo empresa e não o campo company, ou vice versa, quando entrei no painel do usuário no modo admin, ele não cadastrou este campo de texto, e quando eu fui tentar alterar isso pelo frontend, o site não carregou completamente ou rendezirou os htmls, e carregou só até o label Empresa sem o textfield aparecendo e mais nada, sabe se já aconteceu com você isso?

Abs
