### ISSUE TITLE
Alterar campos.

### ISSUE THREAD

**Issue by Strapazzon** [deivisonarthur/OSC-Magento-Brasil#90]
Ola pessoal.
Sou novo aqui estou usando o modulo pela primeira vez, gostaria de parabenizados o modulo esta excelente.
Porem estou com um problema.
estou tentendo alterar o arquivo app\code\local\DeivisonArthur\OnepageCheckout\etc\config.xml

colocar o telefone como opcional, alterei a tag  <phone>required</phone>  para <phone>optional</phone> porem não teve efeito.

**Comment by Randolphlima** [comment]
Olá jovem,
Se eu não me engano, existe essa opção na área administrativa do modulo. Já deu uma olhada la? Você está usando a versão 3.2 ou a 4? Na 3.2 você pode modificar direto na área administrativa, deixando ele como hidden ou opcional.

T+

**Comment by Strapazzon** [comment]
Boa noite!
Obrigado pela dica. realmente estava lá no painel administrativo.
